### PR TITLE
adding data

### PR DESCRIPTION
**Pull request by RichardMoseley**
Please review the added CSV files for animal data. Even if they're not used, they should be a helpful reference.

### CODE REVIEW

**Review by jdean92 — COMMENTED** [review]
looks good

**Comment by SBoyce02** [comment]
ok, with the file adds

**Review by SBoyce02 — APPROVED** [review]
Ok with add

**Review by jdean92 — COMMENTED** [review]
yapr

**Review by jdean92 — APPROVED** [review]

**Pull request merged**
